//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ACTION_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ACTION_TABLE()
        {
            this.PENALTY_TABLE = new HashSet<PENALTY_TABLE>();
        }
    
        public int ID { get; set; }
        public Nullable<int> OBJECT { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<byte> EMPLOYEE { get; set; }
        public Nullable<System.DateTime> BORROWDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
        public Nullable<System.DateTime> MEMBERRETURNDATE { get; set; }
        public Nullable<bool> ACTIONSTATUS { get; set; }
    
        public virtual ADMIN_TABLE ADMIN_TABLE { get; set; }
        public virtual OBJECT_TABLE OBJECT_TABLE { get; set; }
        public virtual MEMBER_TABLE MEMBER_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PENALTY_TABLE> PENALTY_TABLE { get; set; }
    }
}
