//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_TABLE
    {
        public int ID { get; set; }
        public string SENDER { get; set; }
        public string RECEIVER { get; set; }
        public string TOPIC { get; set; }
        public string MESSAGECONTENT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    }
}
