//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class OBJECT_TABLE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OBJECT_TABLE()
        {
            this.ACTION_TABLE = new HashSet<ACTION_TABLE>();
            this.RESERVED_OBJECT_TABLE = new HashSet<RESERVED_OBJECT_TABLE>();
        }
    
        public int ID { get; set; }
        public string NAME { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<bool> STATUS { get; set; }
        public string DETAIL { get; set; }
        public string OBJECTIMAGE { get; set; }
        public Nullable<bool> RESERVATIONSTATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ACTION_TABLE> ACTION_TABLE { get; set; }
        public virtual CATEGORY_TABLE CATEGORY_TABLE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RESERVED_OBJECT_TABLE> RESERVED_OBJECT_TABLE { get; set; }
    }
}
