//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ObjectManagementSystem.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVED_OBJECT_TABLE
    {
        public int ID { get; set; }
        public Nullable<int> OBJECT { get; set; }
        public Nullable<int> MEMBER { get; set; }
        public Nullable<System.DateTime> BORROWDATE { get; set; }
        public Nullable<System.DateTime> RETURNDATE { get; set; }
    
        public virtual MEMBER_TABLE MEMBER_TABLE { get; set; }
        public virtual OBJECT_TABLE OBJECT_TABLE { get; set; }
    }
}
